# Generated by Django 2.2.2 on 2019-07-08 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(verbose_name='动作序号')),
                ('method', models.TextField(verbose_name='标签')),
                ('pid', models.IntegerField(verbose_name='标签序号')),
            ],
        ),
        migrations.CreateModel(
            name='FraudText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textid', models.IntegerField(verbose_name='投诉文本序号')),
                ('text', models.TextField(verbose_name='投诉文本')),
            ],
        ),
        migrations.CreateModel(
            name='TagText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='记录序号')),
                ('textid', models.CharField(max_length=64, verbose_name='投诉文本序号')),
                ('sentid', models.CharField(max_length=64, verbose_name='分句序号')),
                ('text', models.TextField(verbose_name='分句内容')),
                ('secid', models.IntegerField(verbose_name='动作序号')),
                ('tagid', models.IntegerField(verbose_name='标签序号')),
                ('reviewer', models.IntegerField(verbose_name='用户id')),
                ('savedate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='用户序号')),
                ('name', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='用户密码')),
                ('start', models.IntegerField(verbose_name='开始投诉文本序号')),
                ('end', models.IntegerField(verbose_name='结束投诉文本序号')),
            ],
        ),
    ]
