# Generated by Django 2.2.3 on 2019-07-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagtext',
            name='sentid',
            field=models.IntegerField(verbose_name='分句序号'),
        ),
        migrations.AlterField(
            model_name='tagtext',
            name='textid',
            field=models.IntegerField(verbose_name='投诉文本序号'),
        ),
    ]
