# Generated by Django 2.2.3 on 2019-07-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190710_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='记录序号')),
                ('textid', models.IntegerField(verbose_name='投诉文本序号')),
                ('sentid', models.IntegerField(verbose_name='分句序号')),
                ('text', models.TextField(verbose_name='分句内容')),
                ('tagid', models.IntegerField(verbose_name='标签序号')),
            ],
        ),
    ]
